<footer>
<section id="access">
<div class="container">
<h2 class="title"><img src="/common/img/access_title.png" srcset="/common/img/access_title.png 1x, /common/img/access_title_s.png 2x" alt="アクセス" /></h2>
<dl class="adressBox">
<dt class="adressTitle">
<img src="/common/img/address_title.png" alt="Adress" />
</dt>
<dd class="text">
〒812-0024<br />
福岡市博多区綱場町1-17
</dd>
</dl>

<div id="mapCanvas" class="map"></div>
<div id="mapCanvasS" class="map"></div>
<div class="mapText"><a href="https://www.google.co.jp/maps/place/福岡パーキングビル" target="_blank">googlemapで見る</a></div>

<dl class="contactBox">
<dt class="contactTitle">
<img src="/common/img/contact_title.png" alt="Contact" />
</dt>
<dd class="text">
<div class="tel"><img src="/common/img/contact_tel.png" srcset="/common/img/contact_tel.png 1x, /common/img/contact_tel_s.png 2x" alt="tel. 092-271-5022" /></div>
<p>Fax. 092-271-5022<br />
E-mail. <script type="text/javascript">
<!--
function converter(M){
var str="", str_as="";
for(var i=0;i<M.length;i++){
str_as = M.charCodeAt(i);
str += String.fromCharCode(str_as + 1);
}
return str;
}
function mail_to(k_1,k_2)
{eval(String.fromCharCode(108,111,99,97,116,105,111,110,46,104,114,101,102,32,
61,32,39,109,97,105,108,116,111,58) 
+ escape(k_1) + 
converter(String.fromCharCode(104,109,101,110,63,101,44,111,96,113,106,104,109,102,45,98,110,45,105,111,
62,114,116,97,105,100,98,115,60)) 
+ escape(k_2) + "'");} 
document.write('<a href=JavaScript:mail_to("","")><span class="mail"><img src="/common/img/footer_mail.png"></span><\/a>');
//-->
</script>
<noscript><span class="mail"><img src="/common/img/footer_mail.png" /></span></noscript></p>
<p>お問い合わせ受付時間<br />
9:00～17:00（土、日、祝日は除く）</p>
</dd>
</dl>

</div>
</section>
<!--/access-->

<section id="foot">
<div class="container">
<div class="privacyPolicy"><a href="/demo/privacy/">プライバシーポリシー</a></div>
<div class="copyright"><img src="/common/img/copyright.png" alt="Copyright (C) Tada Rinsan Co., Ltd.　All Rights Reserved." /></div>
</div>
</section>
<div id="pageup"><a href="#head"><img src="/common/img/pageup.png" alt="ページの先頭へ" /></a></div>
</footer>

<script type="text/javascript" src="/common/js/assemblyFoot.js"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBZNNOy3dWPFPLXlHsa-ia7U0iFH89Qp6A"></script>