<header id="head">
<h1 class="logo"><a href="./"><img src="/common/img/logo.png" srcset="/common/img/logo.png 1x, /common/img/logo_s.png 2x" alt="天神パーキングビル" /></a></h1>
<div class="hAddressS">〒812-0024 福岡市博多区綱場町1-17</div>

<div class="headBox">
<dl id="hContact">
<dt>お問い合わせ</dt>
<dd>
<p class="tel"><img src="/common/img/header_tel.png" alt="tel.092-271-5022" /></p>
<p class="time">9:00～17:00（土、日、祝日は除く）</p>
</dd>
</dl>

<dl id="hAddress">
<dt>所在地</dt>
<dd>〒812-0024<br />
福岡市博多区綱場町1-17</dd>
</dl>
</div>

<nav id="pcNavi">
<ul>
<li class="parking"><a href="/parking/"><img src="/common/img/menu_parking.png" alt="駐車場・料金" /></a></li>
<li class="room"><a href="/room/"><img src="/common/img/menu_community_room.png" alt="貸会議室" /></a></li>
<li class="garage"><a href="/garage/"><img src="/common/img/menu_bike_garage.png" alt="バイクガレージ" /></a></li>
<li class="company"><a href="/company/"><img src="/common/img/menu_company.png" alt="会社概要" /></a></li>
<li class="contact"><a href="/contact/"><img src="/common/img/menu_contact.png" alt="お問い合わせ" /></a></li>
</ul>
</nav>
<!--/pcNavi-->

<nav id="spNavi">
<div id="spMenuBox" class="mobile-head">
<div id="toggle">
<div>
<span></span>
<span></span>
<span></span>
</div>
<div class="toggleText">メニュー</div>
</div>
<div id="spMenu" class="global-nav">
<ul>
<li class="parking"><a href="/parking/">駐車場・料金</a></li>
<li class="room"><a href="/room/">貸会議室</a></li>
<li class="garage"><a href="/garage/">バイクガレージ</a></li>
<li class="company"><a href="/company/">会社概要</a></li>
<li class="contact"><a href="/contact/">お問い合わせ</a></li>
<li class="contact"><a href="./">トップ</a></li>
</ul>
</div>
</div>

<ul id="spMenuSub">
<li><a href="#access"><img src="/common/img/menu_access_s.png" alt="アクセス" width="130" height="34" /></a></li>
<li><a href="/contact/"><img src="/common/img/menu_contact_s.png" alt="お問い合わせ" /></a></li>
</ul>
</nav>
<!--/spNavi-->
</header>